name: CD

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: 'env (test|stg|prd)'
      account_id:
        required: true
        type: string
        description: 'test 000000000000, stg 111111111111, prd 222222222222'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ${{ inputs.env }} / ${{ inputs.account_id }}
        run: echo "deploy to ${{ inputs.env }} / ${{ inputs.account_id }}"
      - name: Dump github context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

